# Generated by Django 4.2.2 on 2023-08-09 17:49

import django.core.validators
from django.db import migrations, models
import final_exam_project.user_auth_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0003_alter_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=18, validators=[final_exam_project.user_auth_app.models.validate_min_age]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), final_exam_project.user_auth_app.models.validate_string_only_letters]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), final_exam_project.user_auth_app.models.validate_string_only_letters]),
        ),
    ]
