# Generated by Django 4.2.2 on 2023-07-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_car_web', '0003_car_currently_rented'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='car_model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.AddField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
