# Generated by Django 4.2.2 on 2023-08-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_car_web', '0005_rentcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcar',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
