# Generated by Django 4.2.2 on 2023-08-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_car_web', '0007_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcar',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
