# Generated by Django 4.2.2 on 2023-08-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_car_web', '0009_remove_car_created_at_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='currently_rented',
        ),
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-08-04 17:46'),
            preserve_default=False,
        ),
    ]
