# Generated by Django 4.2.2 on 2023-08-05 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_car_web', '0011_delete_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcar',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='rentcar',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
