# Generated by Django 4.2.2 on 2023-08-05 13:53

from django.db import migrations, models
import final_exam_project.rent_a_car_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_car_web', '0012_alter_rentcar_created_at_alter_rentcar_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcar',
            name='price',
            field=models.FloatField(default=0, validators=[final_exam_project.rent_a_car_web.models.validate_not_a_negative_number]),
        ),
    ]
